/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Calculadora.h"

int *
sumar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = argp->arg1 + argp->arg2;

	return &result;
}

int *
restar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = argp->arg1 - argp->arg2;

	return &result;
}

int *
multiplicar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = argp->arg1 * argp->arg2;

	return &result;
}

double *
dividir_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result = (double)argp->arg1 / (double)argp->arg2;

	return &result;
}
